# GitHub Pages Configuration
theme: jekyll-theme-minimal
title: UTI - Educação Médica Gratuita
description: Repositório de aprendizado interativo para estudantes de medicina em Unidade de Terapia Intensiva
