name: Qualidade de Conteúdo

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Executar testes unitários
        run: pytest
      - name: Validar notebooks
        run: |
          mkdir -p build/notebooks
          jupyter nbconvert --to notebook --execute notebooks/*.ipynb --output-dir build/notebooks
